### ISSUE TITLE
Add 'requireCookieConsent' options

### ISSUE THREAD

**Issue by timdreier** [brotkrueml/typo3-matomo-integration#20]
First, thank you for this great extension!

### Is your feature request related to a problem? Please describe.

If you use a cookie banner you Matomo is only allowed to set cookies after the user has given its consent. Matomo Provides the option `_paq.push(['requireCookieConsent']);`, which prevents Cookies until `_paq.push(['setCookieConsentGiven']);` is called.

### Describe the solution you'd like

It would be great to integrate `_paq.push(['requireCookieConsent']);` in the options. This would enable us to use your extension together with any cookie consent solution, e.g. dp_cookieconsent, which calls `_paq.push(['setCookieConsentGiven']);` as soon as the user has given it's consent.

**Comment by brotkrueml** [comment]
@timdreier I added the option "requireCookieConsent". Can you test it, if this satisfies your needs? Just requiring `1.6@dev` for testing purposes should be enough.

**Comment by brotkrueml** [comment]
Available in v1.6.0.
