### ISSUE TITLE
Add 'requireConsent' option

### ISSUE THREAD

**Issue by schmidt-oliver** [brotkrueml/typo3-matomo-integration#23]
Hey @brotkrueml , thank you for your awesome TYPO3 extension.

### Is your feature request related to a problem? Please describe.

Nowadays it is required to have consent to share personal data with third party tools. The matomo function `requireConsent()` adds that option.  

### Describe the solution you'd like

If that option is enabled in site configuration matomo will do nothing until the matomo function `setConsentGiven()` is triggert for example in javascript. Implementation should be same as with `requireCookieConsent()`.

Would be nice if you can add that option. Thank you!

**Comment by brotkrueml** [comment]
Hej @schmidt-oliver,
thank you for your kind words and the feature request. I implemented with #20 the `requireCookieConsent`, but I assume this is not that what you need ;-). Now, I saw in the docs, that there are two consent options: `requireConsent` and `requireCookieConsent`. Of course it makes sense to support also the `requireConsent` option.

Docs: https://developer.matomo.org/4.x/guides/tracking-consent#step-1-require-consent

**Comment by brotkrueml** [comment]
Available in v1.7.0.

**Comment by schmidt-oliver** [comment]
Yes, the difference is that if you use `requireConsent` then matomo will not index at all if consent is not given. If it is given matomo will index and set the cookies.

If you use `requireCookieConsent` instead, matomo will index without cookies and if consent is given, it will set the cookies.

I don't know why matomo decided to use two separate ways instead consent for indexing and on top a consent for using cookies.

Because of the script is loaded from the server, the IP address is always sent to the matomo server. Eventually that could be an issue at all.

Thank you for providing this feature in following version.

**Comment by brotkrueml** [comment]
If you host Matomo yourself, the request to the Matomo server should not be an issue as you have the control over it (and no 3rd party has access to the webserver log files - which contain the IP addresses). It is then the same as a request to the TYPO3 webserver.
