### ISSUE TITLE
[GDPR] delay remote script until consent

### ISSUE THREAD

**Issue by xerc** [brotkrueml/typo3-matomo-integration#27]
@ `_paq[]` ; if `requireConsent` is set (& `setup:url` is "external") ; do not load script until `setConsentGiven`

ref. https://developer.matomo.org/guides/tracking-consent

**Comment by xerc** [comment]
"hide domain" HACK @ .htaccess

`RewriteRule ^matomo\.js$ https://<domain>{REQUEST_URI}? [END]`

**Comment by brotkrueml** [comment]
@xerc As I do not work with `requireConsent` (due to cookieless usage): How would you expect a workflow for this? How should an external URL be recognised? It can be hosted by yourself under a different (sub)domain, so it is not really external, but under your control.

There is also an event which can be used in combination with a consent banner:
https://docs.typo3.org/p/brotkrueml/typo3-matomo-integration/1.8/en-us/UseCases/Index.html#extending-the-script-tag

**Comment by xerc** [comment]
> As I do not work with `requireConsent` (due to cookieless usage)

if the <domain> is on the same system - should be OK cause the "defaults" are already send by the browser

> How would you expect a workflow for this? How should an external URL be recognised? It can be hosted by yourself under a different (sub)domain, so it is not really external, but under your control.

if the <domain> is "external" for expl. @ AWS or even another system (which has different "store" settings)

> There is also an event which can be used in combination with a consent banner: https://docs.typo3.org/p/brotkrueml/typo3-matomo-integration/1.8/en-us/UseCases/Index.html#extending-the-script-tag

two different endpoint inputs should be best
1. JS ; via ReWrite | Copy | ..
2. PHP

**Comment by brotkrueml** [comment]
@xerc Sadly, I don't get what you expect how this should be solved. 

What do you mean with "different store settings"?

I assume, with "endpoint inputs" you mean the URL to the Matomo server? So you suggest two input fields, one for an internal and one for an external URL? And if both are filled, use both?

What should be done, when a Matomo URL is external in contrast to internal?

What do you mean with "JS | via Rewrite | Copy" and "PHP".

Sorry, I really don't get it.

**Comment by xerc** [comment]
`/matomo.js` is loaded BEFORE the user can consent to sending out data ; if the matomo instance is not on the same system (where the requested website is served from) loading this script user-data is send out which is very bad data-protection

1 url / domain-input for the (hopefully) static JS  file `/matomo.js`
1 url / domain-input for the dynamic PHP endpoint `/matomo.php`

**Comment by xerc** [comment]
https://github.com/brotkrueml/typo3-matomo-integration/blob/8bbcd90cef2aba6ca2e083e00365f3237acd0bde/Classes/Code/JavaScriptTrackingCodeBuilder.php#L162
PHP endpoint
https://github.com/brotkrueml/typo3-matomo-integration/blob/8bbcd90cef2aba6ca2e083e00365f3237acd0bde/Classes/Code/JavaScriptTrackingCodeBuilder.php#L163
JS static-file
https://github.com/brotkrueml/typo3-matomo-integration/blob/8bbcd90cef2aba6ca2e083e00365f3237acd0bde/Classes/Code/JavaScriptTrackingCodeBuilder.php#L166

**Comment by brotkrueml** [comment]
> `/matomo.js` is loaded BEFORE the user can consent to sending out data ; if the matomo instance is not on the same system (where the requested website is served from) loading this script user-data is send out which is very bad data-protection

For this the mentioned event is available and the linked scenario is the showcase for this. This way, your consent manager is taking care.

Handling this directly in the extension may be opinionated, which I want to avoid.

What is your suggestion for an implementation?

**Comment by brotkrueml** [comment]
@xerc When setting the option "requireConsent" no tracking request will be sent to Matomo and no cookies will be set.
See: https://developer.matomo.org/guides/tracking-consent#step-1-require-consent

This should solve your issue.

**Comment by xerc** [comment]
> When setting the option "requireConsent" no tracking request will be sent to Matomo and no cookies will be set.

this flag will be checked by the script - if this script is on another infrastructure the browser-data is send before eval.

**Comment by brotkrueml** [comment]
So, you mean the server logs (Apache/nginx/...). What is your suggestion to solve this issue? IMHO this can be solved by a consent manager as already mentioned above.

This extension is meant as a wrapper around the Matomo methods and functionality. I won't add functionality that is the work of a cm - this is out of scope.

**Comment by xerc** [comment]
ok - thx for the exchange // my solution hack'y ..
```
  search.matomo = /(?<=<script>)(if\(typeof _paq[^<]+)/
  replace.matomo = function onCookieStatusChange(status){if(status == 'allow'){$1}}
```
