### ISSUE TITLE
SiteLanguage specific SiteID

### ISSUE THREAD

**Issue by tdoedtmann** [brotkrueml/typo3-matomo-integration#29]
It should be possible to customize the `SiteID` (`matomoIntegrationSiteId`) based on the language of a Page.

In TypoScript it could look something like this (for a quick/rough idea):
```typoscript
[applicationContext == "Production/Live" && siteLanguage("languageId") == 0]
  plugin.tx_matomo_integration.settings.siteId = 1
[end]

[applicationContext == "Production/Live" && siteLanguage("languageId") == 1]
  plugin.tx_matomo_integration.settings.siteId = 5
[end]
```

It cannot currently be solved via events, as the `Configuration` object is declared as `private readonly`.
In addition, I don't know what the performance/caching situation would be here.

**Comment by brotkrueml** [comment]
@tdoedtmann I added an event for manipulating the site configuration on runtime:
https://docs.typo3.org/p/brotkrueml/typo3-matomo-integration/main/en-us/Developer/Index.html#modifysiteconfigurationevent

Please check if this meets your requirements. You can install it with
`composer req brotkrueml/typo3-matomo-integration:^2.1@dev`

**Comment by brotkrueml** [comment]
@tdoedtmann Have you tried it if the change meets your requirements? A feedback is welcome, I can then provide a new release.

**Comment by tdoedtmann** [comment]
@brotkrueml First of all, thank you very much for the (really quick) implementation.  
It works exactly as I needed it to. I was also able to adopt the example 1:1, so from my point of view it can be included in the upcoming release.
