### ISSUE TITLE
Float values not allowed for `addMatomoMethodCall`

### ISSUE THREAD

**Issue by simonschaufi** [brotkrueml/typo3-matomo-integration#30]
### Current behavior

Float values not allowed for `addMatomoMethodCall`. See https://matomo.org/faq/reports/advanced-manually-tracking-ecommerce-actions-in-matomo/#example-of-tracking-the-ecommerce-order

### Expected behavior/output

Allow float values

### Steps to reproduce

```php
$event->addMatomoMethodCall(
            'trackEcommerceOrder',
            "000123", // (Required) orderId
            10.99, // (Required) grandTotal (revenue)
            9.99, // (Optional) subTotal
            1.5, // (optional) tax
            1, // (optional) shipping
            false // (optional) discount
        );
```
### Environment

- Matomo Integration version(s): 2.1.0
- TYPO3 version(s): 11

### Possible Solution

Allow float values

**Comment by brotkrueml** [comment]
@simonschaufi Thanks for the report. Floats are now possible with the 2.1.1 release.
