### ISSUE TITLE
Change site TCA to allow Matomo site IDs to be configured through the environment

### ISSUE THREAD

**Issue by tehplague** [brotkrueml/typo3-matomo-integration#8]
### Is your feature request related to a problem? Please describe.

Currently assigning site IDs through the environment is rather difficult. The site configuration YAML itself supports e.g. setting the site id with something like `%env(MATOMO_SITE_ID)%`. However, as the site IDs TCA field renders a numerical input instead of a text one TYPO3 replaces the environment reference with a 0 when the site configuration is saved later.

### Describe the solution you'd like

Could you change the TCA field definition to allow textual input? You may add a validation for either a numerical input or an `%env(...)%` reference to provide a comparable level of input validation. 

### Describe alternatives you've considered

In the meantime we keep the %env...%-definition. We have to make sure that nobody accidentally commits the removal of the env-reference in the site YAML. :(

**Comment by brotkrueml** [comment]
@tehplague You are absolutely right. there is also a [plugin](https://plugins.matomo.org/ProtectTrackID) available which protects the site id with a hash (which is a string also). If you like, you can provide a PR.

**Comment by brotkrueml** [comment]
@tehplague Site configuration is adjusted, can you test against main branch if this resolves your issue?

**Comment by tehplague** [comment]
Yep, works perfectly. Thank you!
